# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple_calculate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple_calculate.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16simple_calculate.proto\"}\n\x04Work\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\x12\x1b\n\x02op\x18\x03 \x01(\x0e\x32\x0f.Work.Operation\"<\n\tOperation\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\x0c\n\x08SUBTRACT\x10\x01\x12\x0c\n\x08MULTIPLY\x10\x02\x12\n\n\x06\x44IVIDE\x10\x03\"\x15\n\x06Result\x12\x0b\n\x03val\x18\x01 \x01(\x05\"\x17\n\x07Subject\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x0cQuestionType\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x14\n\x05\x44\x65lta\x12\x0b\n\x03val\x18\x01 \x01(\x05\"\x12\n\x03Sum\x12\x0b\n\x03val\x18\x01 \x01(\x05\"\x15\n\x06Number\x12\x0b\n\x03val\x18\x01 \x01(\x05\"#\n\x06\x41nswer\x12\x0b\n\x03val\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t2\xaf\x01\n\x0fSimpleRpcServer\x12\x1d\n\tCalculate\x12\x05.Work\x1a\x07.Result\"\x00\x12\x36\n\x17GetSubjectQuestionTypes\x12\x08.Subject\x1a\r.QuestionType\"\x00\x30\x01\x12\x1e\n\nAccumulate\x12\x06.Delta\x1a\x04.Sum\"\x00(\x01\x12%\n\x0bGuessNumber\x12\x07.Number\x1a\x07.Answer\"\x00(\x01\x30\x01\x62\x06proto3')
)



_WORK_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='Work.Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADD', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUBTRACT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTIPLY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIVIDE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=91,
  serialized_end=151,
)
_sym_db.RegisterEnumDescriptor(_WORK_OPERATION)


_WORK = _descriptor.Descriptor(
  name='Work',
  full_name='Work',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num1', full_name='Work.num1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num2', full_name='Work.num2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op', full_name='Work.op', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WORK_OPERATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=151,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='Result.val', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=174,
)


_SUBJECT = _descriptor.Descriptor(
  name='Subject',
  full_name='Subject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Subject.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=199,
)


_QUESTIONTYPE = _descriptor.Descriptor(
  name='QuestionType',
  full_name='QuestionType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='QuestionType.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=229,
)


_DELTA = _descriptor.Descriptor(
  name='Delta',
  full_name='Delta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='Delta.val', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=251,
)


_SUM = _descriptor.Descriptor(
  name='Sum',
  full_name='Sum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='Sum.val', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=271,
)


_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='Number.val', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=294,
)


_ANSWER = _descriptor.Descriptor(
  name='Answer',
  full_name='Answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='Answer.val', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='Answer.desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=331,
)

_WORK.fields_by_name['op'].enum_type = _WORK_OPERATION
_WORK_OPERATION.containing_type = _WORK
DESCRIPTOR.message_types_by_name['Work'] = _WORK
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['Subject'] = _SUBJECT
DESCRIPTOR.message_types_by_name['QuestionType'] = _QUESTIONTYPE
DESCRIPTOR.message_types_by_name['Delta'] = _DELTA
DESCRIPTOR.message_types_by_name['Sum'] = _SUM
DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
DESCRIPTOR.message_types_by_name['Answer'] = _ANSWER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Work = _reflection.GeneratedProtocolMessageType('Work', (_message.Message,), dict(
  DESCRIPTOR = _WORK,
  __module__ = 'simple_calculate_pb2'
  # @@protoc_insertion_point(class_scope:Work)
  ))
_sym_db.RegisterMessage(Work)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'simple_calculate_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  ))
_sym_db.RegisterMessage(Result)

Subject = _reflection.GeneratedProtocolMessageType('Subject', (_message.Message,), dict(
  DESCRIPTOR = _SUBJECT,
  __module__ = 'simple_calculate_pb2'
  # @@protoc_insertion_point(class_scope:Subject)
  ))
_sym_db.RegisterMessage(Subject)

QuestionType = _reflection.GeneratedProtocolMessageType('QuestionType', (_message.Message,), dict(
  DESCRIPTOR = _QUESTIONTYPE,
  __module__ = 'simple_calculate_pb2'
  # @@protoc_insertion_point(class_scope:QuestionType)
  ))
_sym_db.RegisterMessage(QuestionType)

Delta = _reflection.GeneratedProtocolMessageType('Delta', (_message.Message,), dict(
  DESCRIPTOR = _DELTA,
  __module__ = 'simple_calculate_pb2'
  # @@protoc_insertion_point(class_scope:Delta)
  ))
_sym_db.RegisterMessage(Delta)

Sum = _reflection.GeneratedProtocolMessageType('Sum', (_message.Message,), dict(
  DESCRIPTOR = _SUM,
  __module__ = 'simple_calculate_pb2'
  # @@protoc_insertion_point(class_scope:Sum)
  ))
_sym_db.RegisterMessage(Sum)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), dict(
  DESCRIPTOR = _NUMBER,
  __module__ = 'simple_calculate_pb2'
  # @@protoc_insertion_point(class_scope:Number)
  ))
_sym_db.RegisterMessage(Number)

Answer = _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), dict(
  DESCRIPTOR = _ANSWER,
  __module__ = 'simple_calculate_pb2'
  # @@protoc_insertion_point(class_scope:Answer)
  ))
_sym_db.RegisterMessage(Answer)



_SIMPLERPCSERVER = _descriptor.ServiceDescriptor(
  name='SimpleRpcServer',
  full_name='SimpleRpcServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=334,
  serialized_end=509,
  methods=[
  _descriptor.MethodDescriptor(
    name='Calculate',
    full_name='SimpleRpcServer.Calculate',
    index=0,
    containing_service=None,
    input_type=_WORK,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSubjectQuestionTypes',
    full_name='SimpleRpcServer.GetSubjectQuestionTypes',
    index=1,
    containing_service=None,
    input_type=_SUBJECT,
    output_type=_QUESTIONTYPE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Accumulate',
    full_name='SimpleRpcServer.Accumulate',
    index=2,
    containing_service=None,
    input_type=_DELTA,
    output_type=_SUM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GuessNumber',
    full_name='SimpleRpcServer.GuessNumber',
    index=3,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_ANSWER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMPLERPCSERVER)

DESCRIPTOR.services_by_name['SimpleRpcServer'] = _SIMPLERPCSERVER

# @@protoc_insertion_point(module_scope)
